import os
import glob
import json
from Interpolation.evaluate_nbeats import evaluate


def find_map_files(results_dir):
    patterns = [
        os.path.join(results_dir, 'map_*_outliers_less_test_only.csv'),
        os.path.join(results_dir, 'map_*_outliers_less.csv'),
        os.path.join(results_dir, 'map_*.csv')
    ]
    files = []
    for p in patterns:
        for f in glob.glob(p):
            # ignore merged files
            if '_interpolation' in f or f.endswith('_all_animals.csv'):
                continue
            files.append(f)
    # unique
    files = sorted(list(set(files)))
    return files


def run_for_dataset(file_rawdata_name, file_rawdata_columns, results_root):
    results = []
    models_dir = os.path.join(os.path.dirname(__file__), 'models')
    files = find_map_files(results_root)
    if not files:
        print('No map files found in', results_root)
        return

    for f in files:
        try:
            print('Evaluating', f)
            res = evaluate(f, file_rawdata_name, file_rawdata_columns, model_dir=models_dir)
            # load summary CSV generated by evaluate
            base = os.path.basename(file_rawdata_name).split('.')[0]
            summary_csv = os.path.join(models_dir, f'nbeats_eval_summary_{base}.csv')
            if os.path.exists(summary_csv):
                with open(summary_csv, 'r') as fh:
                    txt = fh.read()
                results.append({'file': f, 'summary_csv': summary_csv})
            else:
                results.append({'file': f, 'result': res})
        except Exception as e:
            print('Error evaluating', f, e)

    # Save a manifest
    out_manifest = os.path.join(models_dir, f'eval_manifest_{os.path.basename(results_root)}.json')
    with open(out_manifest, 'w') as fh:
        json.dump(results, fh, indent=2)

    print('Done. Manifest saved to', out_manifest)


if __name__ == '__main__':
    import sys
    if len(sys.argv) < 4:
        print('Usage: evaluate_all_nbeats.py <rawdata_filename> <rawdata_columns_json> <results_dir>')
        raise SystemExit(1)
    raw = sys.argv[1]
    cols = sys.argv[2]
    results_dir = sys.argv[3]
    run_for_dataset(raw, cols, results_dir)
